### ISSUE TITLE
Graph does not update with state

### ISSUE THREAD

**Issue by guyzk** [aeyrium/bezier-chart#10]
I want to have a few graphs in separate cupertino segment.
When I switch between tabs the chart data is refreshed but the chart remains with the initial data (does not refresh - kind of like a singleton chart)
Each tab has a different date range (monthly, weekly etc...)

**Comment by diegoveloper** [comment]
Could you add a minimum sample code to reproduce the issue here?

**Comment by diegoveloper** [comment]
I updated the package, Could you try using the dependency in this way: 

```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```

And run :  `flutter packages upgrade`  

Let me know if it works.

**Comment by guyzk** [comment]
Unfortunately the new version didn't fix the issue.

The build method:

`  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Container(
          width: double.infinity,
          padding: EdgeInsets.symmetric(horizontal: 24),
          child: CupertinoSegmentedControl(
              unselectedColor: Provider.of<EventerTheme>(context).colorScheme.statisticsSelectedTabText,
              borderColor: Provider.of<EventerTheme>(context).colorScheme.statisticsSelectedTabBg,
              selectedColor: Provider.of<EventerTheme>(context).colorScheme.statisticsSelectedTabBg,
              children: <int, Widget>{
//                DAY: Text(AppLocalizations.of(context).hourly, style: TextStyle(fontWeight: FontWeight.bold)),
                THIRTY_DAYS: Text(AppLocalizations.of(context).pastMonth, style: TextStyle(fontWeight: FontWeight.bold)),
                SIX_MONTHS: Text(AppLocalizations.of(context).pastSixMonths, style: TextStyle(fontWeight: FontWeight.bold)),
              },
              groupValue: _selectedSalesSegment,
              onValueChanged: (int value) {
                setState(() {
                  _selectedSalesSegment = value;
                });
              }),
        ),
//        if(_selectedSalesSegment == DAY)
//          chartByTimeSpan(widget.bloc.pastDaySalesTimeline.stream),
        if (_selectedSalesSegment == THIRTY_DAYS)
          SalesChart(widget.bloc.thirtyDaysSalesTimeline.stream),
        if (_selectedSalesSegment == SIX_MONTHS)
          SalesChart(widget.bloc.sixMonthsSalesTimeline.stream),
      ],
    );
  }`

**Comment by diegoveloper** [comment]
add a minimum sample code to reproduce the issue please.  Did you add the dependency in your pubspec.yaml like I showed you ?

**Comment by guyzk** [comment]
Updated with sample code, and yes, I used the git ref in the pubsec.yaml

**Comment by diegoveloper** [comment]
sorry, I pushed some changes few minutes ago.  Could you try again? 
Don't forget to run :  `flutter packages upgrade` , let me know if it works for you.

**Comment by guyzk** [comment]
It works after the last update!
Thanks a lot.

BTW if you look at the code sample i posted above you can see that I wrapped the BezierChart with a Directionality class.
The reason is since my app works with several languages, a few of which are RTL.
When using the chart with an RTL language the bubbles don't work as they should.
Forcing the chart to LTR fixes this issue.
Just thought you should know.

Thanks again!

**Comment by PlymouthRock** [comment]
I'm having a similar issue.  Updating data. The Y Axis changes, but the Line and Bubble indicator data is not updated until you tap the chart.  Using selectedValue property.  We are also pulling the latest code from master.

**Comment by diegoveloper** [comment]
There are two properties according the chart scale, selectedDate and selectedValue, which scale are you using?

**Comment by PlymouthRock** [comment]
SelectedValue



On Sun, Aug 11, 2019 at 10:14 AM -0400, "Diego Vel?squez L?pez" <notifications@github.com<mailto:notifications@github.com>> wrote:


There are two properties according the chart scale, selectedDate and selectedValue, which scale are you using?

-

**Comment by diegoveloper** [comment]
Which scale are you using?

**Comment by PlymouthRock** [comment]
Custom
