### ISSUE TITLE
Y axis labels are overlaying chart line

### ISSUE THREAD

**Issue by xylish7** [aeyrium/bezier-chart#19]
The problem is that when I start to scroll the chart, the Y axis labels are overlaying the chart line, making it hard to read the labels. 

**Problem:**
![image](https://user-images.githubusercontent.com/24867712/61108398-dfe0bb00-a48a-11e9-9ed6-6ffad29fe8d1.png)

**How it should look:**
![image](https://user-images.githubusercontent.com/24867712/61108682-b4aa9b80-a48b-11e9-9e88-8ee8e6e41dfa.png)

- The chart line should never pass beyound that imaginary white line when scrolling, the solution would be to make only the container of the chart line scrolable and the Y axis labels to be in a different container.

**Comment by diegoveloper** [comment]
Done,  I updated the code, Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

Check the `sample8`

Let me knows if it works.

**Comment by xylish7** [comment]
It seems like the problem persist:
![image](https://user-images.githubusercontent.com/24867712/61174908-7c9c7900-a5af-11e9-95a9-90b6349baebc.png)
Do I need to add a specific property or do something ?

**Comment by diegoveloper** [comment]
Ah backgroundColor or gradient inside BezierChartConfig

**Comment by xylish7** [comment]
It works, however it would be great to control that space with a prop, because , as you can see it's still overlaying the line for longer labels:
![image](https://user-images.githubusercontent.com/24867712/61175422-c0937c00-a5b7-11e9-8bae-289ba62a5f28.png)

**Comment by xylish7** [comment]
And also, using backgroundColor or gradient there is a small portion of the chart line that you can see floating up and down while scrolling the chart. I know it's a small detail but it's there 😂:
![image](https://user-images.githubusercontent.com/24867712/61175635-bbd0c700-a5bb-11e9-9fe7-992696f032e1.png)

**Comment by diegoveloper** [comment]
I pushed some changes , could you try again?  `flutter packages upgrade`

**Comment by xylish7** [comment]
It's ok now, regarding that issue. However it seems like another label was added on my Y axis, without me changing anything to the code. My max value is 100 still there is a 125 which appeared after I run `flutter packages upgrade`
And that little floating dot from the chart line is still present.
![image](https://user-images.githubusercontent.com/24867712/61180410-8610fa00-a61e-11e9-9484-09075cfc7b66.png)

**Comment by diegoveloper** [comment]
Could you try again using `flutter packages upgrade` ?

**Comment by xylish7** [comment]
The problem persists. That '125' value is still there:
![image](https://user-images.githubusercontent.com/24867712/61183147-0c8d0200-a646-11e9-8b63-7088a76e8f7e.png)

**Comment by diegoveloper** [comment]
hmm ok I pushed some changes, try again please: 

`flutter packages upgrade`

**Comment by xylish7** [comment]
It works! Thank you for your time and fast responses! 😁
